# TCL File Generated by Component Editor 18.1
# Thu Jul 25 14:23:55 CEST 2024
# DO NOT MODIFY


# 
# mutrig_reset_controller "MuTRiG Reset Controller" v1.0.8
# Yifeng Wang 2024.07.25.14:23:55
# Issue reset to MuTRiG during run sync. Allows fine phase shift w.r.t a reference clock.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mutrig_reset_controller
# 
set_module_property DESCRIPTION "Issue reset to MuTRiG during run sync. Allows fine phase shift w.r.t a reference clock."
set_module_property NAME mutrig_reset_controller
set_module_property VERSION 1.0.8
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Data Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "MuTRiG Reset Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mutrig_reset_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mutrig_reset_controller.vhd VHDL PATH mutrig_reset_controller.vhd TOP_LEVEL_FILE
add_fileset_file alt_pll_reconfig.vhd VHDL PATH alt_pll_reconfig/alt_pll_reconfig.vhd
add_fileset_file altera_pll_reconfig_core.v VERILOG PATH alt_pll_reconfig/alt_pll_reconfig/altera_pll_reconfig_core.v
add_fileset_file altera_pll_reconfig_top.v VERILOG PATH alt_pll_reconfig/alt_pll_reconfig/altera_pll_reconfig_top.v
add_fileset_file altera_std_synchronizer.v VERILOG PATH alt_pll_reconfig/alt_pll_reconfig/altera_std_synchronizer.v
add_fileset_file alt_pll.vhd VHDL PATH alt_pll/alt_pll.vhd
add_fileset_file alt_pll_0002.v VERILOG PATH alt_pll/alt_pll/alt_pll_0002.v


# 
# parameters
# 
add_parameter RESET_LANE NATURAL 2
set_parameter_property RESET_LANE DEFAULT_VALUE 2
set_parameter_property RESET_LANE DISPLAY_NAME RESET_LANE
set_parameter_property RESET_LANE TYPE NATURAL
set_parameter_property RESET_LANE UNITS None
set_parameter_property RESET_LANE ALLOWED_RANGES 0:2147483647
set_parameter_property RESET_LANE HDL_PARAMETER true
add_parameter DEBUG NATURAL 1
set_parameter_property DEBUG DEFAULT_VALUE 1
set_parameter_property DEBUG DISPLAY_NAME DEBUG
set_parameter_property DEBUG TYPE NATURAL
set_parameter_property DEBUG UNITS None
set_parameter_property DEBUG ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point runcontrol
# 
add_interface runcontrol avalon_streaming end
set_interface_property runcontrol associatedClock dpa_clock
set_interface_property runcontrol associatedReset dpa_reset
set_interface_property runcontrol dataBitsPerSymbol 9
set_interface_property runcontrol errorDescriptor ""
set_interface_property runcontrol firstSymbolInHighOrderBits true
set_interface_property runcontrol maxChannel 0
set_interface_property runcontrol readyLatency 0
set_interface_property runcontrol ENABLED true
set_interface_property runcontrol EXPORT_OF ""
set_interface_property runcontrol PORT_NAME_MAP ""
set_interface_property runcontrol CMSIS_SVD_VARIABLES ""
set_interface_property runcontrol SVD_ADDRESS_GROUP ""

add_interface_port runcontrol asi_runcontrol_data data Input 9
add_interface_port runcontrol asi_runcontrol_valid valid Input 1
add_interface_port runcontrol asi_runcontrol_ready ready Output 1


# 
# connection point reconfig_mgmt
# 
add_interface reconfig_mgmt avalon end
set_interface_property reconfig_mgmt addressUnits WORDS
set_interface_property reconfig_mgmt associatedClock si_direct_clock
set_interface_property reconfig_mgmt associatedReset dpa_reset
set_interface_property reconfig_mgmt bitsPerSymbol 8
set_interface_property reconfig_mgmt burstOnBurstBoundariesOnly false
set_interface_property reconfig_mgmt burstcountUnits WORDS
set_interface_property reconfig_mgmt explicitAddressSpan 0
set_interface_property reconfig_mgmt holdTime 0
set_interface_property reconfig_mgmt linewrapBursts false
set_interface_property reconfig_mgmt maximumPendingReadTransactions 0
set_interface_property reconfig_mgmt maximumPendingWriteTransactions 0
set_interface_property reconfig_mgmt readLatency 0
set_interface_property reconfig_mgmt readWaitTime 1
set_interface_property reconfig_mgmt setupTime 0
set_interface_property reconfig_mgmt timingUnits Cycles
set_interface_property reconfig_mgmt writeWaitTime 0
set_interface_property reconfig_mgmt ENABLED true
set_interface_property reconfig_mgmt EXPORT_OF ""
set_interface_property reconfig_mgmt PORT_NAME_MAP ""
set_interface_property reconfig_mgmt CMSIS_SVD_VARIABLES ""
set_interface_property reconfig_mgmt SVD_ADDRESS_GROUP ""

add_interface_port reconfig_mgmt avs_reconfig_mgmt_address address Input 6
add_interface_port reconfig_mgmt avs_reconfig_mgmt_read read Input 1
add_interface_port reconfig_mgmt avs_reconfig_mgmt_readdata readdata Output 32
add_interface_port reconfig_mgmt avs_reconfig_mgmt_write write Input 1
add_interface_port reconfig_mgmt avs_reconfig_mgmt_writedata writedata Input 32
add_interface_port reconfig_mgmt avs_reconfig_mgmt_waitrequest waitrequest Output 1
set_interface_assignment reconfig_mgmt embeddedsw.configuration.isFlash 0
set_interface_assignment reconfig_mgmt embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment reconfig_mgmt embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment reconfig_mgmt embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dpa_reset
# 
add_interface dpa_reset reset end
set_interface_property dpa_reset associatedClock pll_dynamic_phase_shift_clock
set_interface_property dpa_reset synchronousEdges BOTH
set_interface_property dpa_reset ENABLED true
set_interface_property dpa_reset EXPORT_OF ""
set_interface_property dpa_reset PORT_NAME_MAP ""
set_interface_property dpa_reset CMSIS_SVD_VARIABLES ""
set_interface_property dpa_reset SVD_ADDRESS_GROUP ""

add_interface_port dpa_reset i_lvds_dpa_rst reset Input 1


# 
# connection point dpa_clock
# 
add_interface dpa_clock clock end
set_interface_property dpa_clock clockRate 125000000
set_interface_property dpa_clock ENABLED true
set_interface_property dpa_clock EXPORT_OF ""
set_interface_property dpa_clock PORT_NAME_MAP ""
set_interface_property dpa_clock CMSIS_SVD_VARIABLES ""
set_interface_property dpa_clock SVD_ADDRESS_GROUP ""

add_interface_port dpa_clock i_lvds_dpa_clk clk Input 1


# 
# connection point si_direct_clock
# 
add_interface si_direct_clock clock end
set_interface_property si_direct_clock clockRate 125000000
set_interface_property si_direct_clock ENABLED true
set_interface_property si_direct_clock EXPORT_OF ""
set_interface_property si_direct_clock PORT_NAME_MAP ""
set_interface_property si_direct_clock CMSIS_SVD_VARIABLES ""
set_interface_property si_direct_clock SVD_ADDRESS_GROUP ""

add_interface_port si_direct_clock i_si_direct_clk clk Input 1


# 
# connection point pll_dynamic_phase_shift_clock
# 
add_interface pll_dynamic_phase_shift_clock clock start
set_interface_property pll_dynamic_phase_shift_clock associatedDirectClock ""
set_interface_property pll_dynamic_phase_shift_clock clockRate 0
set_interface_property pll_dynamic_phase_shift_clock clockRateKnown false
set_interface_property pll_dynamic_phase_shift_clock ENABLED true
set_interface_property pll_dynamic_phase_shift_clock EXPORT_OF ""
set_interface_property pll_dynamic_phase_shift_clock PORT_NAME_MAP ""
set_interface_property pll_dynamic_phase_shift_clock CMSIS_SVD_VARIABLES ""
set_interface_property pll_dynamic_phase_shift_clock SVD_ADDRESS_GROUP ""

add_interface_port pll_dynamic_phase_shift_clock o_pll_dps_clk clk Output 1


# 
# connection point mutrig_reset
# 
add_interface mutrig_reset conduit end
set_interface_property mutrig_reset associatedClock dpa_clock
set_interface_property mutrig_reset associatedReset ""
set_interface_property mutrig_reset ENABLED true
set_interface_property mutrig_reset EXPORT_OF ""
set_interface_property mutrig_reset PORT_NAME_MAP ""
set_interface_property mutrig_reset CMSIS_SVD_VARIABLES ""
set_interface_property mutrig_reset SVD_ADDRESS_GROUP ""

add_interface_port mutrig_reset o_mutrig_reset reset Output reset_lane

