alt_pll_reconfig_sim/alt_pll_reconfig.vhd
alt_pll_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_top.v
alt_pll_reconfig_sim/altera_pll_reconfig/altera_pll_reconfig_core.v
alt_pll_reconfig_sim/altera_pll_reconfig/altera_std_synchronizer.v
